### PR TITLE
Add func to retrieve comments

### PR DESCRIPTION
**Pull request by Jleagle**

### CODE REVIEW

**Comment by geraldywy** [comment]
hey @Jleagle, I'm wondering if this feature is good to merge? i am looking to use this feature.

**Comment by Jleagle** [comment]
Should be 👍

**Comment by geraldywy** [comment]
@vartanbeno not sure if you are still actively maintaining this project, could you review this MR? I would like to use this feature if possible, rather than making a call directly to reddit api

**Comment by TonyDMorris** [comment]
just pulled this and tested , it fails on url values being passed a slice , once that is fixed the api returns a 400 , did you even test this against the actual reddit api ?

**Pull request closed without merging**
